const char *strings[47][2] = {
    {"Impostazioni", "settings", },
    {"Diagnosi", "Test", },
    {"Archiviazione", "Archiving", },
    {"Parametri", "Parameters", },
    {"Ingressi", "Inputs", },
    {"Errore di comunicazione", "Communication error", },
    {"Riprova", "Try again", },
    {"Uscite", "Outputs", },
    {"Temperatura", "Temperature", },
    {"Umidita' sonda", "Humidity probe", },
    {"Temperatura sonda", "Temperature probe", },
    {"Motore avanti", "Motor forward", },
    {"Motore indietro", "Motor backward", },
    {"Scelta programma", "Program choice", },
    {"Allarme emergenza!", "Emergency alarm!", },
    {"Cassetto del filtro aperto", "Filter drawer open", },
    {"Oblo' aperto", "Porthole open", },
    {"Asciugatura in corso", "Drying in progress", },
    {"Codice", "Codice", },
    {"Allarme", "Alarm", },
    {"Gettoni", "Coins", },
    {"Digitale", "Digital", },
    {"Linea", "Line", },
    {"Totale", "Total", },
    {"Azzera", "Clear", },
    {"Abilita", "Enable", },
    {"Programmi", "Programs", },
    {"Cancellare il programma?", "Delete the program?", },
    {"CALDO", "HOT", },
    {"MEDIO", "WARM", },
    {"TIEPIDO", "TEPID", },
    {"FREDDO", "COLD", },
    {"LANA", "WHOOL", },
    {"Cancellare il passo?", "Delete the step?", },
    {"Informazioni", "Information", },
    {"Asciugatura", "Drying", },
    {"Raffreddamento", "Cooling", },
    {"Antipiega", "Antifold", },
    {"Flusso d'aria assente", "Air flow missing", },
    {"Blocco bruciatore", "Burner lock", },
    {"Surriscaldamento", "Overheating", },
    {"Cassa", "Cash desk", },
    {"Disabilita", "Disable", },
    {"Avanzate", "Advanced", },
    {"Comunicazione", "Communication", },
    {"Ripristino a impostazioni di fabbrica", "Factory reset", },
    {"Accesso", "Access", },
};

