const char *strings[25][2] = {
    {"Impostazioni", "settings", },
    {"Diagnosi", "Test", },
    {"Archiviazione", "Archiving", },
    {"Parametri", "Parameters", },
    {"Ingressi", "Inputs", },
    {"Errore di comunicazione", "Communication error", },
    {"Riprova", "Try again", },
    {"Uscite", "Outputs", },
    {"Temperatura", "Temperature", },
    {"Motore avanti", "Motor forward", },
    {"Motore indietro", "Motor backward", },
    {"Scelta programma", "Program choice", },
    {"Allarme emergenza!", "Emergency alarm!", },
    {"Cassetto del filtro aperto", "Filter drawer open", },
    {"Oblo' aperto", "Porthole open", },
    {"Asciugatura in corso", "Drying in progress", },
    {"Codice", "Codice", },
    {"Allarme", "Alarm", },
    {"Disabilita", "Disable", },
    {"Avanzate", "Advanced", },
    {"Comunicazione", "Communication", },
    {"Ripristino a impostazioni di fabbrica", "Factory reset", },
    {"Accesso", "Access", },
    {"Programmi", "Programs", },
    {"Cancellare il programma?", "Delete the program?", },
};

