#ifndef AUTOGEN_FILE_STRINGS_H_INCLUDED
#define AUTOGEN_FILE_STRINGS_H_INCLUDED

typedef enum {
    STRINGS_IMPOSTAZIONI = 0,
    STRINGS_DIAGNOSI,
    STRINGS_ARCHIVIAZIONE,
    STRINGS_PARAMETRI,
    STRINGS_INGRESSI,
    STRINGS_ERRORE_DI_COMUNICAZIONE,
    STRINGS_RIPROVA,
    STRINGS_USCITE,
    STRINGS_TEMPERATURA,
    STRINGS_MOTORE_AVANTI,
    STRINGS_MOTORE_INDIETRO,
    STRINGS_SCELTA_PROGRAMMA,
    STRINGS_ALLARME_EMERGENZA,
    STRINGS_CASSETTO_DEL_FILTRO_APERTO,
    STRINGS_OBLO_APERTO,
    STRINGS_ASCIUGATURA_IN_CORSO,
    STRINGS_CODICE,
    STRINGS_ALLARME,
} strings_t;

extern const char *strings[18][2];

#endif
